media:
  label: Media
  input: assets/media
  output: /assets/media__pages
  
content:
  - name: microblogs
    label: Microblogs
    type: collection
    path: content/microblog
    filename: '{year}-{month}-{day}-post.md'
    view:
      fields: [date, tags]
    fields:
      - name: content
        label: Content
        type: rich-text
        required: true
      - name: date
        label: Date
        type: string
        required: true
        pattern:
          message: '[❗] The following pattern must be followed: `[1-12]/[1-31]/[xxxxx] [1-12]:[1-59] [AM/PM]`'
          regex: '\d{1,2}\/\d{1,2}\/\d{4} \d{1,2}:\d{2} [AP]M'
      - name: tags
        label: Tags
        type: string
        list: true
        # pattern:
        #   message: '[❗] The tags must be joined with the "," without any spaces!'
        #   regex: '(?<=\S),(?=\S)'
